import { useEffect, useRef, useState } from 'react';
import { api } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { operations, todayVN, localVN, toInstant, timeVN } from '../services/operations';
import '../styles/operations.css';
const shiftNames={MORNING:'Sáng',AFTERNOON:'Chiều',NIGHT:'Đêm'};
const functions={LEAD:'Phụ trách',RECORDER:'Ghi chính',DUTY:'Trực',SUPPORT:'Hỗ trợ'};
const options=(rows,key='name')=>rows.map(r=><option key={r.id} value={r.id}>{r[key]}</option>);
export default function Operations(){
  const {user,can}=useAuth();const [branchId,setBranch]=useState(user.branchId||''),[meta,setMeta]=useState(null),[businessDate,setDate]=useState(todayVN()),[shiftType,setType]=useState('MORNING'),[shiftId,setShift]=useState(''),[data,setData]=useState(null),[scopeId,setScope]=useState(''),[floorId,setFloor]=useState(''),[tab,setTab]=useState('care'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[lastSync,setSync]=useState(null),[preview,setPreview]=useState(null);
  const [entry,setEntry]=useState({residentId:'',performedByStaffId:'',occurredAt:localVN(),category:'ROUTINE',content:'',taskId:'',requiresHandover:false}),[assignment,setAssignment]=useState({staffId:'',floorId:'',function:'DUTY',startsAt:'',endsAt:''}),[task,setTask]=useState({residentId:'',title:'',dueAt:localVN()}),[transfer,setTransfer]=useState({residentId:'',zoneId:'',floorId:'',roomId:'',bedName:'',effectiveAt:localVN(),reason:''}),[org,setOrg]=useState({kind:'zones',name:'',zoneId:'',floorId:'',isDefault:false}),[schedule,setSchedule]=useState({zoneId:'',shiftType:'MORNING',startTime:'06:00',endTime:'18:00',minimumStaff:0,required:true}),[edit,setEdit]=useState(null),[handoverNote,setHandoverNote]=useState(''),[receivingScopeId,setReceivingScope]=useState(''),[signerStaffId,setSignerStaff]=useState(''),[followups,setFollowups]=useState([]);
  const requestId=useRef(null),generation=useRef(0);
  const branchChoices=user.role==='ADMIN'?null:(user.userScopes?.length?user.userScopes.map(g=>({id:g.branchId,name:g.branchId})):[{id:user.branchId,name:user.branchName}]);
  async function loadMeta(id){const r=await operations('/operations/bootstrap',{query:{branchId:id}});setMeta(r);return r}
  async function refresh(id=shiftId,b=branchId,token=generation.current){if(!id)return;const r=await operations(`/operations/shifts/${id}`,{query:{branchId:b}});if(token!==generation.current)return;setData(r);if(can('FOLLOWUP.VIEW')||can('CSKH.VIEW'))setFollowups(await operations('/follow-ups',{query:{branchId:b}}));setSync(new Date().toISOString());setScope(v=>r.scopes.some(s=>s.id===v)?v:r.scopes[0]?.id||'')}
  useEffect(()=>{let active=true;generation.current++;setMeta(null);setData(null);setShift('');setScope('');setFloor('');setPreview(null);requestId.current=null;setEntry(v=>({...v,residentId:'',performedByStaffId:'',taskId:'',content:''}));
    // Bootstrap obtains allowed branches via user's home branch. Admin selects from BCARE's configured list.
    const init=async()=>{if(branchId){const r=await operations('/operations/bootstrap',{query:{branchId}});if(active)setMeta(r)}else{const r=await api.branches();if(active)setMeta({branches:r.data,zones:[],floors:[],rooms:[],residents:[],staff:[],schedules:[],shifts:[]})}};
    init().catch(e=>active&&setError(e.message));return()=>{active=false};
  },[branchId]);
  useEffect(()=>{generation.current++;setData(null);setPreview(null);const token=generation.current;if(!shiftId)return;refresh(shiftId,branchId,token).catch(e=>token===generation.current&&setError(e.message));const timer=setInterval(()=>refresh(shiftId,branchId,token).catch(e=>token===generation.current&&setError(`Chưa đồng bộ: ${e.message}`)),10000);return()=>clearInterval(timer)},[shiftId,branchId]);
  const scope=data?.scopes.find(s=>s.id===scopeId),open=scope?.status==='OPEN';
  const residents=(data?.residents||[]).filter(r=>r.zoneId===scope?.zoneId&&(!floorId||r.floorId===floorId));
  const assignments=(data?.assignments||[]).filter(a=>a.scopeId===scopeId&&(!floorId||!a.floorId||a.floorId===floorId));
  const activities=(data?.activities||[]).filter(a=>a.scopeId===scopeId&&(!floorId||a.floorId===floorId));
  const floors=(meta?.floors||[]).filter(f=>f.zoneId===scope?.zoneId),zoneFloors=id=>(meta?.floors||[]).filter(f=>f.zoneId===id);
  async function act(fn,text='Đã lưu trên máy chủ.'){setBusy(true);setError('');setMessage('');try{await fn();setMessage(text);if(branchId)await loadMeta(branchId);await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const post=(path,body)=>operations(path,{method:'POST',body:{...body,branchId}});
  async function start(e){e.preventDefault();await act(async()=>{const r=await post('/operations/shifts',{businessDate,shiftType});setShift(r.id)},'Đã mở ca chung của cơ sở.')}
  async function saveEntry(e){e.preventDefault();if(!requestId.current)requestId.current=crypto.randomUUID();await act(async()=>{await post('/operations/activities',{...entry,scopeId,occurredAt:toInstant(entry.occurredAt),clientRequestId:requestId.current});requestId.current=null;setEntry(v=>({...v,content:'',taskId:'',requiresHandover:false}))})}
  const set=(setter,key)=>e=>setter(v=>({...v,[key]:e.target.value}));
  return <section className="op-page"><h1>Sổ bàn giao ca · Khu / tầng</h1><p>Ca chung theo cơ sở; mỗi khu ký và khóa độc lập. Giờ Việt Nam.</p>
    <form className="op-filter" onSubmit={start}><label>Cơ sở<select disabled={busy} value={branchId} onChange={e=>{setBranch(e.target.value);setError('')}}><option value="">Chọn cơ sở</option>{options(meta?.branches||branchChoices||[])}</select></label><label>Ngày ca<input type="date" value={businessDate} onChange={e=>setDate(e.target.value)} required/></label><label>Ca<select value={shiftType} onChange={e=>setType(e.target.value)}>{Object.entries(shiftNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>{can('SHIFT.CREATE')&&<button disabled={busy||!branchId}>Tạo / vào ca chung</button>}<label>Ca đã tạo<select disabled={busy} value={shiftId} onChange={e=>setShift(e.target.value)}><option value="">Chọn ca</option>{(meta?.shifts||[]).sort((a,b)=>b.businessDate.localeCompare(a.businessDate)).map(s=><option key={s.id} value={s.id}>{s.businessDate} · {shiftNames[s.shiftType]} · {s.status}</option>)}</select></label></form>
    {error&&<div className="error" role="alert">{error} Bản đang nhập được giữ; chưa báo lưu thành công.</div>}{message&&<p className="op-success" role="status">{message}</p>}
    <nav className="op-tabs">{[['care','Ghi nhận'],['staff','Nhân sự / phân công'],['tasks','Kế hoạch'],['handover','Bàn giao'],['followups','Việc được giao'],['transfer','Chuyển NCT'],['org','Danh mục / lịch ca']].filter(([id])=>!['tasks','transfer'].includes(id)||can('SHIFT.UPDATE')).filter(([id])=>id!=='followups'||can('FOLLOWUP.VIEW')||can('CSKH.VIEW')).filter(([id])=>id!=='org'||can('SYSTEM.UPDATE')).map(([id,name])=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{name}</button>)}</nav>
    {data&&<><div className="op-scopes">{data.scopes.map(s=><button disabled={busy} key={s.id} className={scopeId===s.id?'selected':''} onClick={()=>{setScope(s.id);setFloor('');setPreview(null);requestId.current=null;setEntry(v=>({...v,residentId:'',performedByStaffId:'',taskId:''}))}}>{s.zoneName} · {s.status}</button>)}</div><div className="op-filter"><strong>{data.shift.businessDate} · {shiftNames[data.shift.shiftType]} · {scope?.zoneName} · {scope?.status}</strong><label>Tầng<select value={floorId} onChange={e=>setFloor(e.target.value)}><option value="">Toàn khu</option>{options(floors)}</select></label><small>Đồng bộ gần nhất {timeVN(lastSync)} · cập nhật mỗi 10 giây</small></div></>}
    {tab==='org'&&meta&&<div className="op-grid"><form className="card op-form" onSubmit={e=>{e.preventDefault();act(()=>post(`/operations/org/${org.kind}`,org))}}><h2>Danh mục khu / tầng / phòng</h2><label>Loại<select value={org.kind} onChange={set(setOrg,'kind')}><option value="zones">Khu</option><option value="floors">Tầng</option><option value="rooms">Phòng</option></select></label><label>Tên<input value={org.name} onChange={set(setOrg,'name')} required/></label>{org.kind!=='zones'&&<label>Khu<select value={org.zoneId} onChange={set(setOrg,'zoneId')} required><option value="">Chọn khu</option>{options(meta.zones)}</select></label>}{org.kind==='rooms'&&<label>Tầng (có thể trống)<select value={org.floorId} onChange={set(setOrg,'floorId')}><option value="">Không chia tầng</option>{options(zoneFloors(org.zoneId))}</select></label>}{org.kind==='zones'&&<label><input type="checkbox" checked={org.isDefault} onChange={e=>setOrg(v=>({...v,isDefault:e.target.checked}))}/> Scope Toàn cơ sở (cơ sở không chia khu)</label>}<button disabled={busy||!branchId}>Thêm danh mục</button><ul>{meta.zones.map(z=><li key={z.id}>{z.name} · {z.active?'Hoạt động':'Ngừng'} <button type="button" onClick={()=>act(()=>post('/operations/org/zones',{...z,active:!z.active}))}>{z.active?'Ngừng hoạt động':'Kích hoạt'}</button></li>)}</ul></form>
      <form className="card op-form" onSubmit={e=>{e.preventDefault();act(()=>post('/operations/org/schedules',schedule))}}><h2>Lịch ca theo khu</h2><label>Khu<select value={schedule.zoneId} onChange={set(setSchedule,'zoneId')} required><option value="">Chọn khu</option>{options(meta.zones.filter(z=>z.active))}</select></label><label>Ca<select value={schedule.shiftType} onChange={set(setSchedule,'shiftType')}>{Object.entries(shiftNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Bắt đầu<input type="time" value={schedule.startTime} onChange={set(setSchedule,'startTime')} required/></label><label>Kết thúc<input type="time" value={schedule.endTime} onChange={set(setSchedule,'endTime')} required/></label><label>Nhân sự tối thiểu<input type="number" min="0" value={schedule.minimumStaff} onChange={set(setSchedule,'minimumStaff')}/></label><button disabled={busy}>Lưu lịch</button><p>Lịch lặp hằng ngày. Ca qua 00:00 thuộc ngày bắt đầu.</p>{meta.schedules.map(s=><p key={s.id}>{meta.zones.find(z=>z.id===s.zoneId)?.name} · {shiftNames[s.shiftType]} · {s.startTime}–{s.endTime} · tối thiểu {s.minimumStaff}</p>)}</form>
      <div className="card"><h2>Danh sách NCT</h2><p>Đồng bộ danh mục BCARE, không tự suy tầng từ tên phòng. Dùng Chuyển NCT để gắn tầng/phòng được xác nhận.</p><button disabled={busy} onClick={()=>act(()=>post('/operations/residents/sync',{}),'Đã đồng bộ danh mục NCT.')}>Đồng bộ NCT</button><button className="secondary" disabled={busy} onClick={()=>act(()=>post('/operations/residents/sync',{allowDemo:true}),'Đã đồng bộ (cho phép dữ liệu demo).')}>Đồng bộ cho chạy thử</button><p>{meta.residents.length} NCT đã có danh mục.</p></div></div>}
    {tab==='care'&&scope&&<div className="op-grid"><form className="card op-form" onSubmit={saveEntry}><h2>Ghi nhận tại {scope.zoneName}</h2><label>NCT<select value={entry.residentId} onChange={set(setEntry,'residentId')} required><option value="">Chọn NCT</option>{residents.map(r=><option key={r.id} value={r.id}>{r.name} · {r.floorName||'Chưa xác định tầng'} · {r.roomName}</option>)}</select></label><label>Người thực hiện<select value={entry.performedByStaffId} onChange={set(setEntry,'performedByStaffId')} required><option value="">Chọn nhân sự được phân công</option>{options([...new Map(assignments.filter(a=>!['ABSENT','CANCELLED','REPLACED'].includes(a.status)).map(a=>[a.staffId,{id:a.staffId,name:a.staffName}])).values()])}</select></label><p>Người nhập: <b>{user.fullName}</b></p><label>Thời điểm thực hiện<input type="datetime-local" value={entry.occurredAt} onChange={set(setEntry,'occurredAt')} required/></label><label>Loại<select value={entry.category} onChange={set(setEntry,'category')}><option value="ROUTINE">Chăm sóc thường quy</option><option value="OBSERVATION">Theo dõi</option><option value="HYGIENE">Vệ sinh</option><option value="TOILETING">Tiêu / tiểu</option><option value="OTHER">Khác</option></select></label><label>Việc liên kết<select value={entry.taskId} onChange={set(setEntry,'taskId')}><option value="">Ghi nhận đột xuất (không hoàn thành kế hoạch)</option>{(data.tasks||[]).filter(t=>t.scopeId===scopeId&&t.residentId===entry.residentId&&t.status==='PENDING').map(t=><option key={t.id} value={t.id}>{t.title} · {timeVN(t.dueAt)}</option>)}</select></label><label>Nội dung<textarea value={entry.content} maxLength={2000} onChange={set(setEntry,'content')} required/></label><label><input type="checkbox" checked={entry.requiresHandover} onChange={e=>setEntry(v=>({...v,requiresHandover:e.target.checked}))}/> Cần chuyển tiếp bàn giao</label><button disabled={busy||!open||!can('CARE.CREATE')}>Lưu ghi nhận</button>{!open&&<p>Khu đã khóa, chỉ đọc.</p>}</form>
      <div className="card"><h2>Hoạt động · {activities.length}</h2>{activities.map(a=><article className="op-log" key={a.id}><strong>{a.residentName}</strong><p>{a.content}</p><small>{timeVN(a.occurredAt)} · {a.floorName||'Chưa xác định tầng'} · làm: {a.performedByStaffName} · nhập: {a.enteredByName}</small>{open&&can('CARE.UPDATE')&&<button onClick={()=>setEdit({id:a.id,expectedVersion:a.version,content:a.content})}>Sửa</button>}</article>)}{edit&&<form className="op-form" onSubmit={e=>{e.preventDefault();act(async()=>{await operations(`/operations/activities/${edit.id}`,{method:'PATCH',body:{...edit,branchId}});setEdit(null)})}}><h3>Sửa ghi nhận · v{edit.expectedVersion}</h3><textarea value={edit.content} maxLength={2000} onChange={set(setEdit,'content')}/><button disabled={busy}>Lưu phiên bản mới</button><button type="button" onClick={()=>setEdit(null)}>Đóng</button></form>}</div></div>}
    {tab==='staff'&&scope&&<><p>Theo phân công; không dùng giờ online để tính hiện diện hoặc lương. Toàn khu có {new Set(assignments.map(a=>a.staffId)).size} nhân sự duy nhất.</p>{can('SHIFT.UPDATE')&&<form className="card op-filter" onSubmit={e=>{e.preventDefault();act(()=>post('/operations/assignments',{...assignment,scopeId,startsAt:assignment.startsAt?toInstant(assignment.startsAt):undefined,endsAt:assignment.endsAt?toInstant(assignment.endsAt):undefined}))}}><label>Nhân viên<select value={assignment.staffId} onChange={set(setAssignment,'staffId')} required><option value="">Chọn nhân sự</option>{options(meta?.staff||[],'fullName')}</select></label><label>Tầng<select value={assignment.floorId} onChange={set(setAssignment,'floorId')}><option value="">Toàn khu</option>{options(floors)}</select></label><label>Chức năng<select value={assignment.function} onChange={set(setAssignment,'function')}>{Object.entries(functions).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Từ (trống = đầu ca)<input type="datetime-local" value={assignment.startsAt} onChange={set(setAssignment,'startsAt')}/></label><label>Đến (trống = cuối ca)<input type="datetime-local" value={assignment.endsAt} onChange={set(setAssignment,'endsAt')}/></label><button disabled={busy||!open}>Phân công</button></form>}
      <div className="op-table"><table><thead><tr><th>Mã / tên</th><th>Khu chính</th><th>Tầng trực</th><th>Chức năng</th><th>Khoảng làm</th><th>Trạng thái</th><th>Làm / nhập</th><th>Điều chỉnh</th></tr></thead><tbody>{assignments.map(a=><tr key={a.id}><td>{a.employeeCode} · {a.staffName}</td><td>{a.homeZoneName||'Chưa xác định'}</td><td>{floors.find(f=>f.id===a.floorId)?.name||'Toàn khu'}</td><td>{functions[a.function]}</td><td>{timeVN(a.startsAt)}–{timeVN(a.endsAt)}</td><td>{a.status}</td><td>{activities.filter(x=>x.performedByStaffId===a.staffId).length} / {activities.filter(x=>x.enteredByUserId===a.linkedUserId).length}</td><td>{open&&can('SHIFT.UPDATE')&&<><select defaultValue="" onChange={e=>{const status=e.target.value;if(!status)return;const reason=window.prompt('Lý do xác nhận/điều chỉnh:');if(reason)act(()=>operations(`/operations/assignments/${a.id}`,{method:'PATCH',body:{branchId,status,reason,expectedVersion:a.version}}));e.target.value=''}}><option value="">Xác nhận trạng thái</option>{['PRESENT','ABSENT','REPLACED','CANCELLED'].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>{const end=window.prompt('Giờ kết thúc phân công (YYYY-MM-DDTHH:mm, giờ Việt Nam):',localVN());const reason=end&&window.prompt('Lý do kết thúc/đổi người:');if(reason)act(()=>operations(`/operations/assignments/${a.id}`,{method:'PATCH',body:{branchId,endsAt:toInstant(end),reason,expectedVersion:a.version}}))}}>Kết thúc / đổi người</button></>}</td></tr>)}</tbody></table></div></>}
    {tab==='tasks'&&scope&&<><form className="card op-filter" onSubmit={e=>{e.preventDefault();act(()=>post('/operations/tasks',{...task,scopeId,dueAt:toInstant(task.dueAt)}))}}><label>NCT<select value={task.residentId} onChange={set(setTask,'residentId')} required><option value="">Chọn NCT</option>{options(residents)}</select></label><label>Việc dự kiến<input value={task.title} maxLength={300} onChange={set(setTask,'title')} required/></label><label>Đến hạn<input type="datetime-local" value={task.dueAt} onChange={set(setTask,'dueAt')} required/></label><button disabled={busy||!open}>Thêm kế hoạch</button></form>{data.tasks.filter(t=>t.scopeId===scopeId).map(t=><p key={t.id}>{t.residentName} · {t.title} · {timeVN(t.dueAt)} · {t.status}</p>)}</>}
    {tab==='handover'&&scope&&<div className="card op-form"><h2>Bàn giao {scope.zoneName}</h2><button disabled={busy} onClick={()=>act(async()=>setPreview(await operations(`/operations/scopes/${scopeId}/handover-preview`,{query:{branchId}})),'Đã tải bản rà soát mới nhất.')}>Rà soát trước khi ký</button>{preview&&<><p>Phiên bản dữ liệu {preview.dataVersion} · {preview.activities.length} ghi nhận · {preview.pendingTasks.length} việc đến hạn chưa xong.</p><ul>{preview.participants.map(a=><li key={a.id}>{a.staffName} · {a.status}</li>)}</ul><p>Danh sách tham gia là snapshot phân công. Người đại diện xác nhận; không coi tick danh sách là chữ ký từng người.</p><label>Người đại diện xác nhận<select value={signerStaffId} onChange={e=>setSignerStaff(e.target.value)}><option value="">Chọn nhân sự đại diện (bắt buộc với CSV)</option>{options([...new Map(preview.participants.filter(a=>!['ABSENT','CANCELLED','REPLACED'].includes(a.status)).map(a=>[a.staffId,{id:a.staffId,name:a.staffName}])).values()])}</select></label><label>Ghi chú / việc chuyển tiếp<textarea value={handoverNote} onChange={e=>setHandoverNote(e.target.value)}/></label>{open&&can('HANDOVER.SIGN')&&<button disabled={busy} onClick={()=>act(async()=>{await post(`/operations/scopes/${scopeId}/sign`,{confirm:true,dataVersion:preview.dataVersion,representativeStaffId:signerStaffId,note:handoverNote});setPreview(null)},'Đã ký và khóa khu này.')}>Xác nhận đã rà soát · ký khu</button>}{preview.handover&&<><p>Đã ký bởi {preview.handover.signedByName} lúc {timeVN(preview.handover.signedAt)}</p><label>Scope ca tiếp theo (ID)<input value={receivingScopeId} onChange={e=>setReceivingScope(e.target.value)} placeholder="Tạo ca tiếp theo, chọn khu và sao chép ID"/></label>{can('HANDOVER.RECEIVE')&&<button disabled={busy||!receivingScopeId} onClick={()=>act(()=>post(`/operations/scopes/${scopeId}/receive`,{confirm:true,receivingScopeId,note:handoverNote}))}>Xác nhận nhận vào ca tiếp theo</button>}</>}</> }<small>Scope hiện tại: {scopeId}</small></div>}
    {tab==='followups'&&<div className="card"><h2>Việc được giao còn theo dõi qua các ca/ngày</h2>{followups.filter(t=>!['CLOSED','CANCELLED'].includes(t.status)).map(t=><article key={t.id} className="op-log"><b>{t.residentName} · {t.title} · {t.status}</b><p>{t.ownerName} · đến hạn {timeVN(t.dueAt)}</p>{can('FOLLOWUP.UPDATE')&&['IN_PROGRESS','RESOLVED'].map(status=><button key={status} onClick={()=>{const note=window.prompt('Kết quả / phản hồi xử lý:');if(note)act(()=>operations(`/follow-ups/${t.id}`,{method:'PATCH',body:{branchId,expectedVersion:t.version,status,note}}))}}>{status==='IN_PROGRESS'?'Tiếp nhận xử lý':'Đã xử lý, chờ CSKH xác minh'}</button>)}</article>)}</div>}
    {tab==='transfer'&&meta&&<form className="card op-form" onSubmit={e=>{e.preventDefault();act(()=>post(`/operations/residents/${transfer.residentId}/transfers`,{...transfer,effectiveAt:toInstant(transfer.effectiveAt)}))}}><h2>Chuyển vị trí NCT</h2><label>NCT<select value={transfer.residentId} onChange={set(setTransfer,'residentId')} required><option value="">Chọn NCT</option>{options(meta.residents)}</select></label><label>Khu đích<select value={transfer.zoneId} onChange={e=>setTransfer(v=>({...v,zoneId:e.target.value,floorId:'',roomId:''}))} required><option value="">Chọn khu</option>{options(meta.zones.filter(z=>z.active))}</select></label><label>Tầng<select value={transfer.floorId} onChange={e=>setTransfer(v=>({...v,floorId:e.target.value,roomId:''}))}><option value="">Không xác định / không chia tầng</option>{options(zoneFloors(transfer.zoneId))}</select></label><label>Phòng<select value={transfer.roomId} onChange={set(setTransfer,'roomId')}><option value="">Chọn phòng nếu có</option>{options(meta.rooms.filter(r=>r.zoneId===transfer.zoneId&&(r.floorId||'')===transfer.floorId))}</select></label><label>Giường<input value={transfer.bedName} onChange={set(setTransfer,'bedName')}/></label><label>Hiệu lực<input type="datetime-local" value={transfer.effectiveAt} onChange={set(setTransfer,'effectiveAt')} required/></label><label>Lý do<textarea value={transfer.reason} onChange={set(setTransfer,'reason')} required/></label><button disabled={busy}>Lưu chuyển vị trí</button><p>Bản ghi cũ giữ vị trí cũ. Việc chưa xong giữ taskId và chuyển sang khu tiếp nhận đã mở.</p></form>}
    {!data&&tab!=='org'&&<div className="card">Chọn ca đã có hoặc cấu hình danh mục → lịch ca → đồng bộ NCT → tạo ca → phân công → ghi nhận.</div>}
  </section>;
}
