import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { api } from '../services/api';

const catLabel={HEALTH:'Sức khỏe',NUTRITION:'Dinh dưỡng / ăn uống',PSYCHOLOGY:'Tâm lý / hành vi',SKIN:'Ngoài da',INCIDENT:'Ngã / sự cố',OTHER:'Khác'};
const urineLabel={NORMAL:'BT',SONDE:'Qua sonde',CATHETER:'Qua ống tiểu',DIAPER:'Qua tã',OTHER:'Khác',LOW:'Tiểu ít',NONE:'Không tiểu'};
const bowelLabel={NORMAL:'Bình thường',CONSTIPATION:'Táo bón',DIARRHEA:'Tiêu chảy',OTHER:'Khác'};
const today=()=>new Date().toLocaleDateString('en-CA');
function vitalText(v){if(!v)return'';return[v.pulse!=null&&`Mạch ${v.pulse}`,v.temperature!=null&&`Nhiệt ${v.temperature}°C`,v.bpSys!=null&&`HA ${v.bpSys}/${v.bpDia}`,v.spo2!=null&&`SpO₂ ${v.spo2}%`,v.respiratoryRate!=null&&`Thở ${v.respiratoryRate}`].filter(Boolean).join(' • ')}
function ImageCell({images,onOpen}){const list=(images||[]).filter(x=>x?.dataUrl||x?.image||typeof x==='string');if(!list.length)return <span>—</span>;return <div className="report-image-strip">{list.map((x,i)=>{const src=typeof x==='string'?x:(x.dataUrl||x.image);return <button type="button" key={i} onClick={()=>onOpen(src)}><img src={src} alt="Ảnh vết loét"/></button>})}</div>}
function formatDate(v){if(!v)return'—';return new Date(`${v}T00:00:00`).toLocaleDateString('vi-VN')}
function formatDateTime(v){if(!v)return'—';return new Date(v).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}

export default function Reports(){
  const [searchParams]=useSearchParams();
  const initial=today();
  const [from,setFrom]=useState(searchParams.get('from')||initial),[to,setTo]=useState(searchParams.get('to')||initial);
  const [d,setD]=useState(null),[branches,setBranches]=useState([]),[branchId,setBranchId]=useState(searchParams.get('branchId')||'');
  const [err,setErr]=useState(''),[q,setQ]=useState(''),[filter,setFilter]=useState('ALL'),[imagePreview,setImagePreview]=useState(null);
  const [residentModal,setResidentModal]=useState(null),[residentLoading,setResidentLoading]=useState(false);
  const rangeLabel=from===to?formatDate(from):`${formatDate(from)} → ${formatDate(to)}`;

  async function load(){try{setErr('');const r=await api.reports(from,to,branchId);setD(r.data)}catch(e){setErr(e.message)}}
  useEffect(()=>{load()},[from,to,branchId]);
  useEffect(()=>{api.branches().then(r=>setBranches(r.data||[])).catch(e=>setErr(e.message))},[]);

  const details=useMemo(()=>{const query=q.trim().toLowerCase();return(d?.details||[]).filter(x=>(filter==='ALL'||filter==='HANDOVER'&&x.requiresHandover||filter==='OPEN'&&x.attentionLevel&&x.attentionStatus==='OPEN'||filter===x.attentionLevel)&&(!query||`${x.residentName} ${x.content} ${x.areaName} ${x.roomName} ${x.createdByName}`.toLowerCase().includes(query)))},[d,q,filter]);

  async function openResident(row){try{setResidentLoading(true);setResidentModal({resident:{id:row.residentId,name:row.residentName,areaName:row.areaName,roomName:row.roomName,bedName:row.bedName},summary:row,changes:[],toileting:[]});const r=await api.residentMedicalReport(row.residentId,from,to);setResidentModal(r.data)}catch(e){setErr(e.message)}finally{setResidentLoading(false)}}
  function exportCsv(){if(!d)return;const rows=[['Ngày giờ','NCT','Khu','Phòng/Giường','Nhóm','Loại','Ưu tiên','Mức cảnh báo','Trạng thái','Nội dung','Sinh hiệu','Xử lý','Người ghi'],...details.map(x=>[formatDateTime(x.occurredAt||x.createdAt),x.residentName,x.areaName||'',`${x.roomName||''} ${x.bedName||''}`,catLabel[x.category]||x.category,x.eventType||'',x.priority||'',x.attentionLevel||'',x.attentionStatus==='RESOLVED'?'Đã xử lý':x.attentionLevel?'Cần xử lý':'',x.content,vitalText(x.vitals),x.intervention||'',x.createdByName||''])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`bcare-bao-cao-bien-dong-${from}-${to}.csv`;a.click()}

  return <section>
    <header className="page-head report-page-head"><div><h1>Báo cáo biến động NCT</h1><p>Tổng hợp biến động chăm sóc theo khoảng ngày, cơ sở và mức cảnh báo. Đây là báo cáo riêng, không gộp với báo cáo ca nhân viên.</p></div><div className="actions report-top-actions"><button className="secondary" onClick={()=>window.print()}>In / PDF</button><button onClick={exportCsv}>Xuất CSV</button></div></header>

    <div className="report-period-panel">
      <div className="report-period-inputs"><label>Từ ngày<input type="date" value={from} onChange={e=>{setFrom(e.target.value);if(to<e.target.value)setTo(e.target.value)}}/></label><label>Đến ngày<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><label>Cơ sở<select value={branchId} onChange={e=>setBranchId(e.target.value)}><option value="">Tất cả cơ sở</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><div className="report-range-summary"><small>Khoảng báo cáo</small><b>{rangeLabel}</b></div></div>
    </div>

    {err&&<div className="error">{err}</div>}
    <div className="report-overview-title"><div><h2>Tổng quan biến động</h2><p>{rangeLabel} · {branchId?(branches.find(b=>b.id===branchId)?.name||'Cơ sở đã chọn'):'Tất cả cơ sở'}</p></div><Link className="secondary button-link" to={`/reports/staff?branchId=${encodeURIComponent(branchId)}&from=${from}&to=${to}`}>Sang báo cáo ca nhân viên →</Link></div>

    <div className="stats stats-6 report-kpis"><div className="stat"><b>{d?.uniqueResidents??'—'}</b><span>NCT có phát sinh</span></div><div className="stat"><b>{d?.changes??'—'}</b><span>Lượt biến động</span></div><div className="stat danger-stat"><b>{d?.openRed??'—'}</b><span>Đỏ chưa xử lý</span></div><div className="stat warning-stat"><b>{d?.openYellow??'—'}</b><span>Vàng chưa xử lý</span></div><div className="stat success-stat"><b>{d?.resolvedToday??'—'}</b><span>Đã xử lý trong kỳ</span></div><div className="stat"><b>{d?.toiletingAbnormal??'—'}</b><span>Tiêu/tiểu lưu ý</span></div></div>

    <div className="panel resident-overview-panel"><div className="panel-title"><div><h2>NCT cần xem trước</h2><p>Ưu tiên Đỏ → Vàng → số lượng biến động. Bấm NCT để xem diễn tiến chi tiết trong đúng khoảng ngày.</p></div><span className="status-summary">{(d?.residentSummaries||[]).length} NCT</span></div><div className="resident-report-grid">{(d?.residentSummaries||[]).map(r=><button className={`resident-report-card ${r.redOpen?'risk-red':r.yellowOpen?'risk-yellow':''}`} key={r.residentId} onClick={()=>openResident(r)}><div className="resident-report-card-head"><div><b>{r.residentName}</b><small>{[r.areaName,r.roomName,r.bedName].filter(Boolean).join(' • ')||'Chưa có vị trí'}</small></div>{r.redOpen>0?<span className="attention-status RED">{r.redOpen} Đỏ</span>:r.yellowOpen>0?<span className="attention-status YELLOW">{r.yellowOpen} Vàng</span>:<span className="resident-ok">Ổn</span>}</div><div className="resident-mini-stats"><span><b>{r.changeCount}</b> biến động</span><span><b>{r.handoverCount}</b> bàn giao</span><span><b>{r.toiletingAbnormal}</b> tiêu/tiểu lưu ý</span></div><div className="resident-last-event"><small>Gần nhất {r.lastEventAt?formatDateTime(r.lastEventAt):'—'}</small><p>{r.lastContent||'Chưa có biến động trong kỳ'}</p>{r.latestVitals&&<em>{vitalText(r.latestVitals)}</em>}</div></button>)}</div>{!(d?.residentSummaries||[]).length&&<div className="empty compact">Không có NCT trong khoảng đã chọn.</div>}</div>

    <div className="panel outstanding-panel"><div className="panel-title"><div><h2>Cảnh báo còn tồn</h2><p>Đỏ/Vàng chưa xử lý được đưa lên trước để quản lý nhìn thấy ngay.</p></div><span className="status-summary">{(d?.outstanding||[]).length} việc</span></div><div className="table-wrap flat"><table><thead><tr><th>Mức</th><th>NCT / vị trí</th><th>Phát sinh</th><th>Nội dung</th><th>Ảnh</th><th>Mở ca</th></tr></thead><tbody>{(d?.outstanding||[]).map(x=><tr key={x.id}><td><span className={`attention-status ${x.attentionLevel}`}>{x.attentionLevel}</span></td><td><button className="link-button" onClick={()=>openResident(x)}><b>{x.residentName}</b></button><small>{x.areaName} • {x.roomName} • {x.bedName}</small></td><td>{formatDateTime(x.occurredAt||x.createdAt)}</td><td>{x.content}<small>{vitalText(x.vitals)}</small></td><td><ImageCell images={x.woundImages||[x.image]} onOpen={setImagePreview}/></td><td><Link className="shift-open-link" to={`/shifts/${x.shiftId}?residentId=${encodeURIComponent(x.residentId)}`}>Xử lý →</Link></td></tr>)}</tbody></table></div>{!d?.outstanding?.length&&<div className="empty compact success-empty">✓ Không còn cảnh báo chờ xử lý.</div>}</div>

    <div className="report-filters"><input placeholder="Tìm NCT, nội dung, khu, người ghi..." value={q} onChange={e=>setQ(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">Tất cả biến động</option><option value="OPEN">Chưa xử lý</option><option value="RED">Mức Đỏ</option><option value="YELLOW">Mức Vàng</option><option value="HANDOVER">Cần bàn giao</option></select><span>{details.length} bản ghi</span></div>
    <div className="dashboard-grid"><div className="panel"><h2>Theo nhóm biến động</h2>{Object.entries(d?.byCategory||{}).map(([k,v])=><div className="bar-row" key={k}><span>{catLabel[k]||k}</span><b>{v}</b></div>)}</div><div className="panel"><h2>Theo khu</h2>{Object.entries(d?.byArea||{}).map(([k,v])=><div className="bar-row" key={k}><span>{k}</span><b>{v}</b></div>)}</div></div>

    <div className="panel"><div className="panel-title"><div><h2>Chi tiết biến động</h2><p>Ngày + giờ, NCT, cảnh báo, nội dung, xử lý, ảnh và người ghi trên cùng một dòng.</p></div><span>{details.length} dòng</span></div><div className="table-wrap flat"><table><thead><tr><th>Ngày giờ</th><th>NCT</th><th>Mức / trạng thái</th><th>Nội dung và xử lý</th><th>Ảnh</th><th>Người ghi</th></tr></thead><tbody>{details.map(x=><tr key={x.id}><td>{formatDateTime(x.occurredAt||x.createdAt)}</td><td><button className="link-button resident-name-link" onClick={()=>openResident(x)}><b>{x.residentName}</b></button><small>{x.areaName||'—'} • {x.roomName||'—'} • {x.bedName||'—'}</small></td><td>{x.attentionLevel?<><span className={`attention-status ${x.attentionLevel}`}>{x.attentionLevel}</span><small>{x.attentionStatus==='RESOLVED'?'Đã xử lý':'Cần xử lý'}</small></>:<span className="badge">Thông thường</span>}</td><td>{x.content}<small>{vitalText(x.vitals)}</small>{x.intervention&&<small><b>Xử lý:</b> {x.intervention}</small>}{x.resolutionNote&&<small className="resolution-text"><b>Kết quả:</b> {x.resolutionNote}</small>}</td><td><ImageCell images={x.woundImages} onOpen={setImagePreview}/></td><td>{x.createdByName||'—'}</td></tr>)}</tbody></table></div>{!details.length&&<div className="empty compact">Không có biến động phù hợp.</div>}</div>

    <div className="panel"><h2>Chi tiết tiêu / tiểu</h2><div className="table-wrap flat"><table><thead><tr><th>Ngày giờ</th><th>NCT</th><th>Tiêu</th><th>Tiểu</th><th>Ghi chú</th><th>Người ghi</th></tr></thead><tbody>{(d?.toiletingDetails||[]).map(x=><tr key={x.id}><td>{formatDateTime(x.createdAt)}</td><td><button className="link-button" onClick={()=>openResident(x)}><b>{x.residentName}</b></button><small>{x.areaName} • {x.roomName} • {x.bedName}</small></td><td>{bowelLabel[x.bowelStatus]||x.bowelStatus}</td><td>{urineLabel[x.urineStatus]||x.urineStatus}</td><td>{[x.urineDetail,x.note].filter(Boolean).join(' • ')||'—'}</td><td>{x.createdByName}</td></tr>)}</tbody></table></div></div>

    {residentModal&&<div className="modal" onClick={()=>setResidentModal(null)}><div className="modal-card resident-report-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><h2>{residentModal.resident?.name||'Chi tiết NCT'}</h2><p>{[residentModal.resident?.areaName,residentModal.resident?.roomName,residentModal.resident?.bedName].filter(Boolean).join(' • ')} · {rangeLabel}</p></div><button className="secondary" onClick={()=>setResidentModal(null)}>Đóng</button></div>{residentLoading?<div className="empty">Đang tải hồ sơ...</div>:<><div className="resident-modal-kpis"><span><b>{residentModal.summary?.changes||0}</b>Biến động</span><span className="red"><b>{residentModal.summary?.openRed||residentModal.summary?.redOpen||0}</b>Đỏ mở</span><span className="yellow"><b>{residentModal.summary?.openYellow||residentModal.summary?.yellowOpen||0}</b>Vàng mở</span><span><b>{residentModal.summary?.handover||residentModal.summary?.handoverCount||0}</b>Cần bàn giao</span><span><b>{residentModal.summary?.toiletingAbnormal||0}</b>Tiêu/tiểu lưu ý</span></div><div className="resident-timeline"><h3>Diễn tiến chăm sóc</h3>{(residentModal.changes||[]).map(x=><div className={`timeline-item ${x.attentionLevel||''}`} key={x.id}><div className="timeline-time">{formatDateTime(x.occurredAt||x.createdAt)}</div><div className="timeline-body"><div className="timeline-title"><b>{catLabel[x.category]||x.category||'Biến động'}</b>{x.attentionLevel&&<span className={`attention-status ${x.attentionLevel}`}>{x.attentionLevel}</span>}</div><p>{x.content}</p>{vitalText(x.vitals)&&<small>{vitalText(x.vitals)}</small>}{x.intervention&&<small><b>Xử lý:</b> {x.intervention}</small>}{x.resolutionNote&&<small><b>Kết quả:</b> {x.resolutionNote}</small>}<div className="timeline-meta">Người ghi: {x.createdByName||'—'}</div><ImageCell images={x.woundImages} onOpen={setImagePreview}/></div></div>)}{!(residentModal.changes||[]).length&&<div className="empty compact">Không có biến động trong kỳ.</div>}<h3>Tiêu / tiểu</h3>{(residentModal.toileting||[]).map(x=><div className="timeline-item" key={x.id}><div className="timeline-time">{formatDateTime(x.createdAt)}</div><div className="timeline-body"><p><b>Tiêu:</b> {bowelLabel[x.bowelStatus]||x.bowelStatus} · <b>Tiểu:</b> {urineLabel[x.urineStatus]||x.urineStatus}</p><small>{[x.urineDetail,x.note].filter(Boolean).join(' • ')||'Không ghi chú'}</small></div></div>)}</div></>}</div></div>}
    {imagePreview&&<div className="modal image-modal-top" onClick={()=>setImagePreview(null)}><div className="modal-card image-preview-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>Ảnh vết loét / tổn thương da</h2><button className="secondary" onClick={()=>setImagePreview(null)}>Đóng</button></div><img src={imagePreview} alt="Ảnh tổn thương da"/></div></div>}
  </section>
}
