import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {api} from '../services/api';
import '../styles/operations.css';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const shiftLabel=t=>({MORNING:'Ca sáng',AFTERNOON:'Ca chiều',NIGHT:'Ca tối'}[t]||t);
const statusLabel=s=>({OPEN:'Đang mở · dữ liệu đang cập nhật',HANDOVER_CONFIRMED:'Đã ký bàn giao',RECEIVED:'Đã nhận bàn giao',CLOSED:'Đã đóng'}[s]||s);
const time=v=>v&&!Number.isNaN(Date.parse(v))?new Date(v).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'—';
const categories={HEALTH:'Sức khỏe',NUTRITION:'Dinh dưỡng',INCIDENT:'Sự cố',PSYCHOLOGY:'Tâm lý',SKIN:'Ngoài da',OTHER:'Khác'};
const bowel={NORMAL:'Bình thường',CONSTIPATION:'Táo bón',DIARRHEA:'Tiêu chảy',OTHER:'Khác'};
const urine={NORMAL:'Bình thường',SONDE:'Qua sonde',CATHETER:'Qua ống tiểu',DIAPER:'Qua tã',OTHER:'Khác',LOW:'Tiểu ít',NONE:'Không tiểu'};
const vitalFields=[['pulse','Mạch','lần/phút'],['temperature','Nhiệt độ','°C'],['bpSys','HA tâm thu','mmHg'],['bpDia','HA tâm trương','mmHg'],['spo2','SpO₂','%'],['respiratoryRate','Nhịp thở','lần/phút'],['bloodGlucose','Đường huyết','mg/dL'],['insulinDoseUnits','Insulin','IU']];
export default function ShiftHistory(){
 const {id}=useParams();const [draft,setDraft]=useState({from:today(),to:today(),shiftType:''}),[filter,setFilter]=useState({from:today(),to:today(),shiftType:''}),[rows,setRows]=useState([]),[report,setReport]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[resident,setResident]=useState(''),[mode,setMode]=useState('all');
 useEffect(()=>{let active=true;setLoading(true);setError('');setReport(null);setRows([]);setResident('');setMode('all');(id?api.shiftHistoryDetail(id):api.shiftHistory(filter)).then(r=>{if(active){id?setReport(r.data):setRows(r.data||[]);setLoading(false)}}).catch(e=>{if(active){setError(e.message);setLoading(false)}});return()=>{active=false}},[id,filter,refresh]);
 const changes=(report?.changes||[]).filter(r=>(!resident||String(r.residentId)===resident)&&(mode==='all'||mode==='followup'&&r.requiresHandover||mode==='open'&&r.attentionLevel&&r.attentionStatus==='OPEN'||mode==='resolved'&&r.attentionStatus==='RESOLVED'));
 const toilets=(report?.toileting||[]).filter(r=>!resident||String(r.residentId)===resident);
 const residentOptions=[...new Map([...(report?.residents||[]).map(r=>[String(r.residentId),r.fullName]),...(report?.changes||[]).map(r=>[String(r.residentId),r.residentName]),...(report?.toileting||[]).map(r=>[String(r.residentId),r.residentName])]).entries()];
 function dayOffset(n){const d=new Date(`${today()}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+n);const value=d.toISOString().slice(0,10);const next={...draft,from:value,to:value};setDraft(next);setFilter(next)}
 return <section className="op-page"><header className="page-head"><div><h1>{report?`${shiftLabel(report.shift.shiftType)} · ${report.shift.shiftDate}`:'Báo cáo từng ca'}</h1><p>Ca sáng và ca tối cùng xem lại diễn biến, xử lý và nội dung bàn giao trong cơ sở được giao.</p>{report&&<p>{report.shift.branchName} · {report.shift.areaName||'Toàn cơ sở'} · <b>{statusLabel(report.shift.status)}</b></p>}</div><div className="actions">{id&&<Link className="button-link secondary" to="/shift-history">← Chọn ca khác</Link>}<Link className="button-link secondary" to="/shifts/current">Về ca chăm sóc</Link><button className="secondary" onClick={()=>setRefresh(v=>v+1)}>Tải lại</button></div></header>
 {!id&&<form className="card op-filter" onSubmit={e=>{e.preventDefault();setFilter({...draft})}}><label>Từ ngày<input type="date" required value={draft.from} onChange={e=>setDraft(v=>({...v,from:e.target.value}))}/></label><label>Đến ngày<input type="date" required value={draft.to} onChange={e=>setDraft(v=>({...v,to:e.target.value}))}/></label><label>Ca<select value={draft.shiftType} onChange={e=>setDraft(v=>({...v,shiftType:e.target.value}))}><option value="">Tất cả ca</option><option value="MORNING">Ca sáng</option><option value="NIGHT">Ca tối</option><option value="AFTERNOON">Ca chiều (dữ liệu cũ)</option></select></label><button>Áp dụng</button><button type="button" className="secondary" onClick={()=>dayOffset(0)}>Hôm nay</button><button type="button" className="secondary" onClick={()=>dayOffset(-1)}>Hôm qua</button></form>}
 {error&&<p className="error" role="alert">{error}</p>}{loading&&<p>Đang tải báo cáo ca…</p>}
 {!id&&!loading&&!error&&<div className="cards">{rows.map(s=><article className="card" key={s.id}><h2>{shiftLabel(s.shiftType)} · {s.shiftDate}</h2><p>{s.branchName} · {s.areaName||'Toàn cơ sở'}</p><p>{statusLabel(s.status)}</p><p>{s.summary.rosterResidents} NCT trong danh sách · {s.summary.records} ghi nhận · {s.summary.openRed+s.summary.openYellow} cảnh báo chưa xử lý · {s.summary.requiresHandover} ghi nhận cần bàn giao</p><Link className="button-link" to={`/shift-history/${encodeURIComponent(s.id)}`}>Xem báo cáo chi tiết</Link></article>)}{!rows.length&&<p className="empty">Chưa có ca phù hợp trong khoảng ngày đã chọn.</p>}</div>}
 {report&&<><p>Đọc dữ liệu đã lưu lúc {time(report.asOf)}. Nhấn Tải lại để xem ghi nhận mới. Báo cáo chỉ xem.</p><div className="op-kpis">{[['NCT trong danh sách',report.summary.rosterResidents],['NCT có ghi nhận',report.summary.residentsWithActivity],['Lượt ghi nhận',report.summary.records],['Đỏ chưa xử lý',report.summary.openRed],['Vàng chưa xử lý',report.summary.openYellow],['Cảnh báo đã xử lý',report.summary.resolvedAlerts],['Ghi nhận cần bàn giao',report.summary.requiresHandover],['Ghi nhận tiêu / tiểu',report.summary.toiletingRecords]].map(([name,value])=><article key={name}><span>{name}</span><strong>{value}</strong></article>)}</div>
 <div className="card"><h2>Nhân sự và bàn giao</h2><p><b>Nhân sự trực:</b> {(report.shift.assignedStaff||[]).map(s=>s.fullName).join(', ')||report.shift.assignedStaffNames?.join(', ')||'Chưa có thông tin'}</p><p><b>Người ghi chính:</b> {report.shift.primaryRecorderName||report.shift.assignedStaffName||'Chưa có thông tin'}</p><p><b>Nội dung bàn giao:</b> {report.handover?.summaryNote||'Chưa có nội dung bàn giao'}</p><p><b>Người ký giao:</b> {report.handover?.confirmedByName||'—'} · {time(report.handover?.confirmedAt)}</p><p><b>Người nhận:</b> {report.handover?.receivedByName||'—'} · {time(report.handover?.receivedAt)}</p></div>
 <div className="card op-filter"><label>NCT<select value={resident} onChange={e=>setResident(e.target.value)}><option value="">Tất cả NCT</option>{residentOptions.map(([key,name])=><option key={key} value={key}>{name||key}</option>)}</select></label><label>Ghi nhận<select value={mode} onChange={e=>setMode(e.target.value)}><option value="all">Tất cả ghi nhận</option><option value="open">Cảnh báo chưa xử lý</option><option value="resolved">Cảnh báo đã xử lý</option><option value="followup">Cần bàn giao / theo dõi tiếp</option></select></label></div>
 <h2>Diễn biến và xử lý trong ca</h2>{changes.map(r=><article className="card op-log" key={r.id}><h3>{r.residentName||'NCT'} · {time(r.occurredAt||r.createdAt)}</h3><p>{[r.areaName,r.roomName,r.bedName].filter(Boolean).join(' · ')} · {(r.categoryCodes||[r.category]).map(c=>categories[c]||c).join(', ')}</p><p><b>Ghi nhận:</b> {r.content||'Chưa có nội dung'}</p><p><b>Đã can thiệp / xử lý:</b> {r.intervention||'Chưa ghi nội dung xử lý'}</p>{r.attentionLevel&&<p><b>Cảnh báo:</b> {r.attentionLevel==='RED'?'Đỏ':'Vàng'} · {r.attentionStatus==='RESOLVED'?'Đã xác nhận xử lý':'Chưa xác nhận xử lý'}</p>}{r.resolutionNote&&<p><b>Kết quả xử lý:</b> {r.resolutionNote}</p>}{r.attentionStatus==='RESOLVED'&&<p><b>Xác nhận xử lý:</b> {r.resolvedByName||'—'} · {time(r.resolvedAt||r.attentionResolvedAt)}</p>}<p><b>Đã báo cho:</b> {r.notifiedTo||'Chưa ghi'}</p>{r.requiresHandover&&<p className="op-warning"><b>Ca sau cần theo dõi:</b> {r.followUp||'Có yêu cầu bàn giao, chưa ghi chi tiết'}</p>}{r.vitals&&<p><b>Sinh hiệu:</b> {vitalFields.filter(([k])=>r.vitals[k]!=null).map(([k,n,u])=>`${n}: ${r.vitals[k]} ${u}`).join(' · ')||'Chưa ghi chỉ số'}</p>}<p><b>Người thực hiện:</b> {r.performerStaffName||'Chưa xác định'} · <b>Người ghi:</b> {r.createdByName||'—'}</p>{r.woundImages?.length>0&&<div className="wound-image-grid saved">{r.woundImages.map(i=>(i.dataUrl||i.url)&&<a key={i.id} href={i.dataUrl||i.url} target="_blank" rel="noreferrer"><img src={i.dataUrl||i.url} alt={`Ảnh tổn thương ${r.residentName}`}/></a>)}</div>}</article>)}{!changes.length&&<p className="empty">Không có ghi nhận phù hợp; không suy ra NCT đã được chăm sóc đầy đủ.</p>}
 <h2>Tiêu / tiểu trong ca</h2>{toilets.map(r=><article className="card op-log" key={r.id}><b>{r.residentName} · {time(r.createdAt)}</b><p>{[r.areaName,r.roomName,r.bedName].filter(Boolean).join(' · ')}</p><p>Tiêu: {bowel[r.bowelStatus]||r.bowelStatus} · Tiểu: {urine[r.urineStatus]||r.urineStatus} {r.urineDetail}</p><p>{r.note||'Không có ghi chú'}</p><small>Người ghi: {r.createdByName||'—'}</small></article>)}{!toilets.length&&<p>Chưa có ghi nhận tiêu / tiểu phù hợp.</p>}
 </>}
 </section>;
}
