import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import express from 'express';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'care-work-access-'));process.env.SHIFTCARE_DATA_DIR=dir;process.env.DATABASE_URL='';
const {default:core}=await import('../src/routes/core.routes.js');const {default:history}=await import('../src/routes/shift-history.routes.js');const {saveUsers,updateStore,getStore}=await import('../src/services/store.service.js');const {signUser}=await import('../src/middleware/auth.js');
const admin={id:'a',role:'ADMIN',active:true,fullName:'Admin'},care={id:'c',username:'csv_NT',fullName:'Chăm sóc viên Nguyễn Tuấn',role:'CARE_SHARED',branchId:'b',active:true,permissions:['SHIFT.VIEW','CARE.VIEW','CARE.CREATE']};const oldToken=signUser({...care,permissions:['SHIFT.VIEW','CARE.VIEW']});await saveUsers([admin,care]);
await updateStore(s=>{s.shifts=['open','broken','signed'].map(id=>({id,branchId:'b',status:id==='broken'?'HANDOVER_CONFIRMED':'OPEN',shiftDate:'2026-10-07',shiftType:'MORNING'}));s.shiftResidents=s.shifts.map(sh=>({id:'r-'+sh.id,shiftId:sh.id,branchId:'b',residentId:'r',fullName:'NCT'}));s.changeLogs=[];s.toiletingLogs=[];s.handovers=[{id:'h',shiftId:'signed',confirmedAt:'2026-10-07T03:00:00Z',confirmedByName:'Người đã ký'}];s.auditLogs=[]});
const app=express();app.use(express.json());app.use('/api/shift-history',history);app.use('/api',core);app.use((e,req,res,next)=>res.status(e.status||500).json({message:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const call=async(method,url,token=oldToken,body)=>{const r=await fetch(`http://127.0.0.1:${server.address().port}/api${url}`,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return{status:r.status,body:await r.json()}};
const payload=shiftId=>({shiftId,residentId:'r',category:'HEALTH',categoryCodes:['HEALTH'],residentStatus:'IN_FACILITY',priority:'LOW',content:'NCT ăn kém',intervention:'Đã hỗ trợ ăn',occurredAt:new Date().toISOString()});
try{
 await test('Care staff with refreshed DB permissions can add/edit unsigned OPEN shift; report view does not lock it',async()=>{const d=await call('GET','/shifts/open');assert.equal(d.status,200);assert.equal(d.body.data.workAccess.canCreate,true);assert.equal(d.body.data.workAccess.canUpdate,true);assert.equal((await call('GET','/shift-history/open')).status,200);assert.equal((await getStore()).shifts.find(s=>s.id==='open').status,'OPEN');const created=await call('POST','/change-logs',oldToken,payload('open'));assert.equal(created.status,201);assert.equal((await call('PATCH',`/change-logs/${created.body.data.id}`,oldToken,{content:'NCT ăn đủ nửa suất'})).status,200)});
 await test('Actual signature blocks writes even if status is inconsistent OPEN; repair cannot bypass a real signature',async()=>{const d=await call('GET','/shifts/signed');assert.equal(d.body.data.workAccess.hasSignature,true);assert.equal(d.body.data.workAccess.canCreate,false);assert.equal((await call('POST','/change-logs',oldToken,payload('signed'))).status,422);assert.equal((await call('POST','/shifts/signed/repair-unconfirmed',signUser(admin),{})).status,409)});
 await test('Only Admin repairs unsigned locked status; afterward care staff can record and audit is saved',async()=>{assert.equal((await call('POST','/shifts/broken/repair-unconfirmed',oldToken,{})).status,403);assert.equal((await call('GET','/shifts/broken',signUser(admin))).body.data.workAccess.canRepair,true);assert.equal((await call('POST','/shifts/broken/repair-unconfirmed',signUser(admin),{})).status,200);assert.equal((await call('POST','/change-logs',oldToken,payload('broken'))).status,201);assert.ok((await getStore()).auditLogs.some(a=>a.action==='SHIFT_REPAIR_UNCONFIRMED'))});
}finally{await new Promise(r=>server.close(r));await fs.rm(dir,{recursive:true,force:true})}
