import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { operations, localVN, toInstant, timeVN } from '../services/operations';
export default function CustomerPanel({branchId,residentId,meta,onClose}){
  const {can}=useAuth(),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[interaction,setInteraction]=useState({channel:'PHONE',contactName:'',content:'',occurredAt:localVN()}),[task,setTask]=useState({title:'',ownerId:'',dueAt:localVN()}),[update,setUpdate]=useState({id:'',status:'IN_PROGRESS',note:''});
  async function load(){setData(await operations(`/cskh/residents/${residentId}/timeline`,{query:{branchId}}))}
  useEffect(()=>{let active=true;operations(`/cskh/residents/${residentId}/timeline`,{query:{branchId}}).then(r=>active&&setData(r)).catch(e=>active&&setError(e.message));return()=>{active=false}},[branchId,residentId]);
  const field=(setter,key)=>e=>setter(v=>({...v,[key]:e.target.value}));
  async function save(path,body,method='POST'){setBusy(true);setError('');try{await operations(path,{method,body:{...body,branchId,residentId}});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <div className="card op-form"><div className="op-filter"><h2>CSKH · {data?.resident?.name||residentId}</h2><button onClick={onClose}>Đóng</button></div>{error&&<p className="error">{error}</p>}
    {can('CSKH.CREATE')&&<div className="op-grid"><form className="op-form" onSubmit={e=>{e.preventDefault();save('/cskh/interactions',{...interaction,occurredAt:toInstant(interaction.occurredAt)})}}><h3>Trao đổi với gia đình</h3><label>Kênh<select value={interaction.channel} onChange={field(setInteraction,'channel')}><option value="PHONE">Điện thoại</option><option value="VISIT">Gặp trực tiếp</option><option value="MESSAGE">Tin nhắn</option><option value="OTHER">Khác</option></select></label><label>Người liên hệ<input value={interaction.contactName} onChange={field(setInteraction,'contactName')}/></label><label>Thời điểm<input type="datetime-local" value={interaction.occurredAt} onChange={field(setInteraction,'occurredAt')} required/></label><label>Nội dung / kết quả<textarea value={interaction.content} maxLength={2000} onChange={field(setInteraction,'content')} required/></label><button disabled={busy}>Lưu tương tác</button></form>
    <form className="op-form" onSubmit={e=>{e.preventDefault();save('/follow-ups',{...task,dueAt:toInstant(task.dueAt)})}}><h3>Giao việc theo dõi</h3><label>Tên việc<input value={task.title} maxLength={300} onChange={field(setTask,'title')} required/></label><label>Người nhận<select value={task.ownerId} onChange={field(setTask,'ownerId')} required><option value="">Chọn người nhận</option>{(meta?.users||[]).map(u=><option key={u.id} value={u.id}>{u.fullName}</option>)}</select></label><label>Hạn xử lý<input type="datetime-local" value={task.dueAt} onChange={field(setTask,'dueAt')} required/></label><button disabled={busy}>Giao tác vụ</button></form></div>}
    <h3>Tác vụ · giữ qua các ngày</h3>{data?.followups.map(t=><article key={t.id} className="op-log"><b>{t.title} · {t.status}</b><p>{t.ownerName} · đến hạn {timeVN(t.dueAt)}</p>{t.history.map((h,i)=><small key={i}>{timeVN(h.at)} · {h.to}: {h.note}</small>)}{can('CSKH.UPDATE')&&<button onClick={()=>setUpdate({id:t.id,expectedVersion:t.version,status:'IN_PROGRESS',note:''})}>Cập nhật xử lý</button>}</article>)}
    {update.id&&<form className="op-form" onSubmit={e=>{e.preventDefault();save(`/follow-ups/${update.id}`,update,'PATCH')}}><label>Trạng thái<select value={update.status} onChange={field(setUpdate,'status')}><option value="IN_PROGRESS">Đang xử lý</option><option value="RESOLVED">Đã xử lý, chờ xác minh</option><option value="CLOSED">Xác minh / đóng</option><option value="OPEN">Mở lại</option><option value="CANCELLED">Hủy</option></select></label><label>Kết quả / lý do<textarea value={update.note} onChange={field(setUpdate,'note')} required/></label><button disabled={busy}>Lưu trạng thái</button></form>}
    <h3>Timeline chăm sóc</h3>{data?.activities.map(a=><article key={a.id} className="op-log"><b>{timeVN(a.occurredAt)} · {a.zoneName} / {a.floorName||'Chưa xác định tầng'}</b><p>{a.content}</p><small>Làm: {a.performedByStaffName} · nhập: {a.enteredByName} · lưu {timeVN(a.savedAt)}</small></article>)}<h3>Lịch sử trao đổi</h3>{data?.interactions.map(i=><article className="op-log" key={i.id}><b>{timeVN(i.occurredAt)} · {i.channel} · {i.contactName}</b><p>{i.content}</p><small>{i.enteredByName}</small></article>)}
  </div>;
}
